### ISSUE TITLE
artwork: night light - icon is not in Mint-Y style

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint22.1-beta#10]
Earlier @mtwebster  had told me that there were problems with the icon border for the Mint-Y theme,  so I made this new icon by modifying an existing one. I hope this version will be useful :

[new.scalable_cs-nightlight__Mint.Y.zip](https://github.com/user-attachments/files/18071563/new.scalable_cs-nightlight__Mint.Y.zip)

PS. Speaking of icons, Have you thought about adding symbolic icons to the power profile options (I mean the ones that show up when you left click on the battery icon) ?.  

![power options](https://github.com/user-attachments/assets/7701964e-9d76-465b-91e3-bbded7b97ec7)

Here are some of them: [power profile symbolic.zip](https://github.com/user-attachments/files/18071598/power.profile.symbolic.zip)

**Comment by clefebvre** [comment]
Can you make a pull request for this? It would need a cs-nightlight.svg in mint-y-icons/src/categories like this one: 

https://github.com/linuxmint/mint-y-icons/blob/master/src/categories/cs-backgrounds.svg

With the different sizes, not just a single SVG (that would lead to pixelation).

**Comment by clefebvre** [comment]
For the power-profiles, it would look too crowded in the menu with the radio buttons. These icons could be used in the panel (it's the case with @rcalixte's applet) but we already show the battery power there.

Joseph is working on an all-in-one applet which might replace all of this, but that's not until the next dev cycle.

**Comment by haggen88** [comment]
@clefebvre  here the [night light icon ](https://github.com/linuxmint/mint-y-icons/pull/452) , I hope everything is ok. Regarding the power profile icons perhaps adding an option to display it in the panel would be a good idea.

**Comment by clefebvre** [comment]
There's a bit of an issue at the moment because the power applet's visibility depends on the presence of a battery. The all-in-one applet will solve that. In the meantime there's already an applet in spices for that:

https://cinnamon-spices.linuxmint.com/applets/view/369
