### ISSUE TITLE
mintinstall: flatpak app icons not displayed

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint22.1-beta#11]
![no icon for flatpaks](https://github.com/user-attachments/assets/80357519-3436-4749-a4c4-3d06f02047df)

mint@mint:~$ mintinstall
MintInstall: low resolution detected (768px height), limiting window height.
MintInstall: Detected system architecture: 'x86_64'
mint-common (WARN): Could not mmap appstream xml file for remote 'flathub': No locales set and using NATIVE_LANGS
MintInstall: No new reviews
MintInstall: Deleting old screenshots
Mintinstall startup took 3197.289 ms

![Untitled](https://github.com/user-attachments/assets/d8d65f22-eb14-4d0c-a908-d7032753612e)

Screenshots and app description are not shown either.

---

At the time of testing flathub.org is operational.
![status](https://github.com/user-attachments/assets/633d41f5-613d-40ec-82e3-5b29b0f694b0)

**Comment by haggen88** [comment]
@mtwebster application icons are now shown, but the app names are still shown with their ID “urls type”:

mint@mint:~$ mintinstall
MintInstall: low resolution detected (768px height), limiting window height.
MintInstall: Detected system architecture: 'x86_64'
MintInstall: No new reviews
MintInstall: Deleting old screenshots
Mintinstall startup took 3989.414 ms
Discovered addon: org.gimp.GIMP.Manual
Discovered addon: org.gimp.GIMP.Plugin.BIMP
Discovered addon: org.gimp.GIMP.Plugin.FocusBlur
Discovered addon: org.gimp.GIMP.Plugin.Fourier
Discovered addon: org.gimp.GIMP.Plugin.GMic
Discovered addon: org.gimp.GIMP.Plugin.Lensfun
Discovered addon: org.gimp.GIMP.Plugin.LiquidRescale
Discovered addon: org.gimp.GIMP.Plugin.Resynthesizer


![sin nombre1](https://github.com/user-attachments/assets/859d67f3-c6c9-4493-ad6c-8fe568a6d394)

![sin nombre](https://github.com/user-attachments/assets/17f0f89b-5dbf-4680-b0dc-0ae160d0b043)

**Comment by mtwebster** [comment]
Try refreshing the cache from the menu

**Comment by haggen88** [comment]
I confirm... the cache had to be updated.
