### ISSUE TITLE
The lock screen does not work

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint22.1-beta#12]
When trying to lock the screen the clock is displayed but at the slightest movement of the touchpad/mouse/keyboard the desktop is displayed again without asking for any password.

[xsession-errors.txt.zip](https://github.com/user-attachments/files/18080456/xsession-errors.txt.zip) shows:

cinnamon-screensaver: no process found
mate-screensaver: no process found
light-locker: no process found

Otherwise, this test was performed in live-usb.

**Comment by mtwebster** [comment]
This is normal in the Live session - the lock screen is disabled.
