### ISSUE TITLE
calendar applet: Formatting info hint links to unavailable site

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint22.1-beta#13]
I use a vertical panel and due to it having some weird issues, I need to modify most elements of it. Calendar applet is in such a need because it displays the hour in a different way - https://github.com/orgs/linuxmint/discussions/411

If I remember correctly, in previous versions when clicking the button below 2 input boxes, it just showed a hint with a formatting info, but now it just opens Firefox and leads to unavailable website:
![Zrzut ekranu z 2024-12-10 13-58-11](https://github.com/user-attachments/assets/10bd0e4e-b818-4b7d-bd20-3a787fe17a79)

**Comment by clefebvre** [comment]
Fixed
