### ISSUE TITLE
system settings color: color details asks for a missing gnome-color-manager

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint22.1-beta#14]
After fresh install when you go to system settings and color section the show details button asks for a missing gnome-color-manager dependency. I don't remember how it worked in Mint 22, but I definitely don't remember it ever asking for that. Maybe it was included before?
![Zrzut ekranu z 2024-12-10 13-54-55](https://github.com/user-attachments/assets/27778a41-9aba-4471-900c-ce044fd26b23)

**Comment by mtwebster** [comment]
The "View details" button actually did nothing before, as the old install prompt was broken. This is working correctly (the gnome app is not installed by default).

**Comment by Qronikarz** [comment]
Alright.
Then what about maybe including it by default so it can be used in live usb when offline? It wasn't a big download so shouldn't make a big difference in .iso size.
