### ISSUE TITLE
Community website, ISO Images section questions

### ISSUE THREAD

**Issue by Qronikarz** [linuxmint/mint22.1-beta#17]
Was wondering about it for a while.
![Zrzut ekranu z 2024-12-10 23-25-36](https://github.com/user-attachments/assets/9e3495ea-b38f-4c9c-93a0-9ab8f86c89a3)
1. `#010` doesn't have a `:` after it
2. There are 3 `#010`s
3. The tasks are not sorted by any sorting method - neither numeric, alphabetical numeric or even normal alphabetical order.

Is there some reason for those things or is it just a leftover from something?

**Comment by clefebvre** [comment]
They're sorted by number. The number doesn't really number otherwise and doesn't need to be unique.
