### ISSUE TITLE
Accessing directory e.g. /root doesn't show prompt for Administrator password when double clicking

### ISSUE THREAD

**Issue by xeroscope-oneshot** [linuxmint/mint22.1-beta#18]
![Screenshot from 2024-12-10 17-01-31](https://github.com/user-attachments/assets/4df3dd21-5f07-460c-8fa0-d9a6dc7ac7dd)
![Screenshot from 2024-12-10 17-01-38](https://github.com/user-attachments/assets/cf87c6fd-e795-48f9-9466-33d66dd34c63)
It only shows when double clicking on restricted directory e.g. /root
But when using right-click/open it show the enter password dialog
_________________________________________________________________________________________________________________________________
System:
  Kernel: 6.8.0-50-generic arch: x86_64 bits: 64 compiler: gcc v: 13.3.0 clocksource: tsc
  Desktop: Cinnamon v: 6.4.2 tk: GTK v: 3.24.41 wm: Muffin v: 6.4.1 dm: LightDM v: 1.30.0
    Distro: Linux Mint 22.1 Xia base: Ubuntu 24.04 noble
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: N/A
  Mobo: ASUSTeK model: ROG STRIX B550-F GAMING (WI-FI) v: Rev X.0x serial: <filter> part-nu: SKU
    uuid: ff2962bb-eb77-84b2-6008-f02f741d79a4 UEFI: American Megatrends v: 3611 date: 09/29/2024
Battery:
  Device-1: hidpp_battery_0 model: Logitech G305 Lightspeed Wireless Gaming Mouse serial: <filter>
    charge: 100% (should be ignored) rechargeable: yes status: discharging
CPU:
  Info: 16-core model: AMD Ryzen 9 5950X bits: 64 type: MT MCP smt: enabled arch: Zen 3+ rev: 2
    cache: L1: 1024 KiB L2: 8 MiB L3: 64 MiB
  Speed (MHz): avg: 2387 high: 3400 min/max: 2200/5083 boost: enabled volts: 1.1 V
    ext-clock: 100 MHz cores: 1: 2200 2: 2200 3: 3400 4: 2200 5: 3400 6: 2200 7: 2200 8: 2200 9: 2200
    10: 2200 11: 2200 12: 2200 13: 2200 14: 2200 15: 2200 16: 2200 17: 2200 18: 2200 19: 3400
    20: 3400 21: 2200 22: 3400 23: 2200 24: 2200 25: 2200 26: 2200 27: 2200 28: 2200 29: 2200
    30: 2200 31: 2200 32: 2200 bogomips: 217190
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA GA106 [GeForce RTX 3060 Lite Hash Rate] vendor: ASUSTeK driver: nvidia
    v: 550.120 arch: Ampere pcie: speed: 5 GT/s lanes: 16 ports: active: none off: HDMI-A-1
    empty: DP-1,DP-2,DP-3 bus-ID: 07:00.0 chip-ID: 10de:2504 class-ID: 0300
  Display: server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X: loaded: nouveau
    unloaded: fbdev,modesetting,vesa failed: nvidia gpu: nvidia,nvidia-nvswitch display-ID: :0
    screens: 1
  Screen-1: 0 s-res: 3840x2160 s-dpi: 159 s-size: 613x360mm (24.13x14.17") s-diag: 711mm (27.99")
  Monitor-1: HDMI-0 res: 3840x2160 hz: 60 dpi: 160 size: 608x355mm (23.94x13.98")
    diag: 704mm (27.72") modes: N/A
  API: EGL v: 1.5 hw: drv: nvidia platforms: device: 0 drv: nvidia device: 2 drv: swrast gbm:
    drv: kms_swrast surfaceless: drv: nvidia x11: drv: nvidia inactive: wayland,device-1
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 550.120 glx-v: 1.4 direct-render: yes
    renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
Audio:
  Device-1: NVIDIA GA106 High Definition Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel
    pcie: speed: 16 GT/s lanes: 16 bus-ID: 07:00.1 chip-ID: 10de:228e class-ID: 0403
  Device-2: AMD Starship/Matisse HD Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel pcie:
    speed: 16 GT/s lanes: 16 bus-ID: 09:00.4 chip-ID: 1022:1487 class-ID: 0403
  API: ALSA v: k6.8.0-50-generic status: kernel-api
  Server-1: PipeWire v: 1.0.5 status: n/a (root, process) with: 1: pipewire-pulse status: active
    2: wireplumber status: active 3: pipewire-alsa type: plugin
Network:
  Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel pcie: speed: 5 GT/s lanes: 1
    bus-ID: 05:00.0 chip-ID: 8086:2723 class-ID: 0280
  IF: wlp5s0 state: down mac: <filter>
  Device-2: Intel Ethernet I225-V vendor: ASUSTeK driver: igc v: kernel pcie: speed: 5 GT/s
    lanes: 1 port: N/A bus-ID: 06:00.0 chip-ID: 8086:15f3 class-ID: 0200
  IF: enp6s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Bluetooth:
  Device-1: Intel AX200 Bluetooth driver: btusb v: 0.8 type: USB rev: 2.0 speed: 12 Mb/s lanes: 1
    bus-ID: 1-5:5 chip-ID: 8087:0029 class-ID: e001
  Report: hciconfig ID: hci0 rfk-id: 1 state: up address: <filter> bt-v: 5.2 lmp-v: 11
    sub-v: 2184 hci-v: 11 rev: 2184 class-ID: 7c0104
Drives:
  Local Storage: total: 2.66 TiB used: 614.28 GiB (22.6%)
  ID-1: /dev/nvme0n1 vendor: Western Digital model: WD BLACK SN770 1TB size: 931.51 GiB
    speed: 63.2 Gb/s lanes: 4 tech: SSD serial: <filter> fw-rev: 731100WD temp: 33.9 C scheme: GPT
  ID-2: /dev/nvme1n1 vendor: Samsung model: MZQLB1T9HAJR-00007 size: 1.75 TiB speed: 31.6 Gb/s
    lanes: 4 tech: SSD serial: <filter> fw-rev: EDA5702Q temp: 33.9 C scheme: GPT
Partition:
  ID-1: / size: 915.32 GiB used: 34.8 GiB (3.8%) fs: ext4 dev: /dev/nvme0n1p2
  ID-2: /boot/efi size: 511 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 0 KiB (0.0%) priority: -2 file: /swapfile
USB:
  Hub-1: 1-0:1 info: hi-speed hub with single TT ports: 10 rev: 2.0 speed: 480 Mb/s lanes: 1
    chip-ID: 1d6b:0002 class-ID: 0900
  Hub-2: 1-3:2 info: Dell USB 2.0 Hub [MTT] ports: 4 rev: 2.0 speed: 480 Mb/s lanes: 1
    power: 100mA chip-ID: 413c:1010 class-ID: 0900
  Device-1: 1-3.4:4 info: Dell Wired Multimedia Keyboard type: keyboard,mouse
    driver: hid-generic,usbhid interfaces: 2 rev: 1.1 speed: 1.5 Mb/s lanes: 1 power: 98mA
    chip-ID: 413c:2110 class-ID: 0301
  Device-2: 1-4:3 info: Logitech USB Receiver type: keyboard,mouse,HID
    driver: logitech-djreceiver,usbhid interfaces: 3 rev: 2.0 speed: 12 Mb/s lanes: 1 power: 98mA
    chip-ID: 046d:c53f class-ID: 0300
  Device-3: 1-5:5 info: Intel AX200 Bluetooth type: bluetooth driver: btusb interfaces: 2
    rev: 2.0 speed: 12 Mb/s lanes: 1 power: 100mA chip-ID: 8087:0029 class-ID: e001
  Device-4: 1-6:6 info: ASUSTek AURA LED Controller type: HID driver: hid-generic,usbhid
    interfaces: 2 rev: 2.0 speed: 12 Mb/s lanes: 1 power: 16mA chip-ID: 0b05:1939 class-ID: 0300
    serial: <filter>
  Hub-3: 1-7:7 info: Genesys Logic Hub ports: 4 rev: 2.0 speed: 480 Mb/s lanes: 1 power: 100mA
    chip-ID: 05e3:0610 class-ID: 0900
  Device-1: 1-7.3:8 info: ENE LianLi-UNI FAN-AL V2-v0.4 type: HID driver: hid-generic,usbhid
    interfaces: 2 rev: 2.0 speed: 12 Mb/s lanes: 1 power: 16mA chip-ID: 0cf2:a104 class-ID: 0300
    serial: <filter>
  Hub-4: 2-0:1 info: super-speed hub ports: 4 rev: 3.1 speed: 10 Gb/s lanes: 1 chip-ID: 1d6b:0003
    class-ID: 0900
  Hub-5: 3-0:1 info: hi-speed hub with single TT ports: 4 rev: 2.0 speed: 480 Mb/s lanes: 1
    chip-ID: 1d6b:0002 class-ID: 0900
  Hub-6: 4-0:1 info: super-speed hub ports: 4 rev: 3.1 speed: 10 Gb/s lanes: 1 chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: 49.5 C mobo: N/A gpu: nvidia temp: 44 C
  Fan Speeds (rpm): N/A gpu: nvidia fan: 0%
Repos:
  Packages: 2097 pm: dpkg pkgs: 2091 pm: flatpak pkgs: 6
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/brave-browser-release.list
    1: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https: //brave-browser-apt-release.s3.brave.com/ stable main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //fastly.linuxmint.io xia main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu noble main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu noble-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu noble-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
Info:
  Memory: total: 64 GiB available: 62.7 GiB used: 3.19 GiB (5.1%)
  Processes: 531 Power: uptime: 28m states: freeze,mem suspend: deep wakeups: 0
    hibernate: disabled Init: systemd v: 255 target: graphical (5) default: graphical
  Compilers: gcc: 13.2.0 Client: Unknown python3.12 client inxi: 3.3.34
___________________________________________________________________________________________________________________________________

**Comment by clefebvre** [comment]
The access denied dialog is normal, but only once polkit authentication fails.

Trying this on a fresh 22.1 installation, both `right-click /root -> Open as Root` and `double-click on /root `succeed in showing the Cinnamon polkit agent authentication dialog.

**Comment by clefebvre** [comment]
What does `` getent passwd `whoami` `` say?

**Comment by xeroscope-oneshot** [comment]
Running as $USERNAME
joseph@KingMackerel:\~$ getent passwd `whoami`
joseph:x:1000:1000:Joseph Ferguson,,,:/home/joseph:/bin/bash
Running as root
root@KingMackerel:\~# getent passwd `whoami`
root:x:0:0:root:/root:/bin/bash

**Comment by clefebvre** [comment]
Are you logging in as root ? (from the login screen I mean). Do you have automatic login set up or are you using a password to log in?

**Comment by xeroscope-oneshot** [comment]
Using a password to login

**Comment by clefebvre** [comment]
Are you logging in as root ? (from the login screen I mean).

**Comment by xeroscope-oneshot** [comment]
Not as root

**Comment by clefebvre** [comment]
This should be fixed in Cinnamon 6.4.3.
