### ISSUE TITLE
LibreOffice: some icons are not displayed when changing to dark theme

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint22.1-beta#20]
When changing to a dark theme, visibility of several icons is lost, unless you manually choose the “Colibre (dark)” theme.

![LO clear](https://github.com/user-attachments/assets/73c3e685-7ef6-4a52-a83d-15f1f1f5339a)

![LO dark](https://github.com/user-attachments/assets/c4b668f4-052b-47b9-b693-d5bdd5510d39)

![LO colibre dark](https://github.com/user-attachments/assets/c5965dbd-b985-41ff-a859-df6d7d79ccc0)

**Comment by clefebvre** [comment]
That's upstream from us. There's no much we can do on this unfortunately. LO doesn't follow the system icon theme, they use their own theme and it doesn't work well automatically.
