### ISSUE TITLE
cinnamon: Radius issues in the default theme

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/mint22.1-beta#23]
I see 2 bugs in the Cinnamon theme:
1- Preview of the grouped window list with square corners as shown in the image below:
![WhatsApp Image 2024-12-12 at 04 46 48](https://github.com/user-attachments/assets/63999d09-32e0-46b9-bb6b-96556c00cd5a)

2- On the right side of the submenu the rounded corners are defective compared to the left side as shown in the image below:
![WhatsApp Image 2024-12-12 at 04 47 15](https://github.com/user-attachments/assets/d1aa09fe-9e9f-441d-baf2-a1d1e3d8bf63)

**Comment by ghost** [comment]
I don't know if this related, but Cinnamon window corners in 22.1 are much less rounded than in 22. Aren't they supposed to be more rounded or at least the same? The start menu in 22.1 is indeed more rounded though, for contrast. And the window widgets are smaller in 22.1, which makes them a bit harder to click.

Edit: Mint-L-Dark-Aqua for Applications and Mint-Y-Dark-Aqua Desktop on both.

![Mint-22-vs-22 1-beta-windows-corners](https://github.com/user-attachments/assets/1aad498c-27b2-4b76-a564-6f71b27c9076)

**Comment by JosephMcc** [comment]
I have a fix for both of the two original issues. I'll push them this weekend.

**Comment by JosephMcc** [comment]
Submitted PR's to fix both issues.

**Comment by clefebvre** [comment]
> I don't know if this related, but Cinnamon window corners in 22.1 are much less rounded than in 22. Aren't they supposed to be more rounded or at least the same? The start menu in 22.1 is indeed more rounded though, for contrast. And the window widgets are smaller in 22.1, which makes them a bit harder to click.
> 
> Edit: Mint-L-Dark-Aqua for Applications and Mint-Y-Dark-Aqua Desktop on both.
> 

I think that's Mint-Y on the left, and Mint-L on the right. These are GTK themes though, it's not related to this issue.
