### ISSUE TITLE
cinnamon: dialog fade is animated even when animations are disabled

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint22.1-beta#24]
I strongly dislike the "secure desktop" effect when a password dialog pops up and would like to disable that, just have the password dialog without blurring the desktop. It's one of the first things I disable in Windows, as I find this effect extremely unpleasant. Thanks!

**Comment by clefebvre** [comment]
Hi @AdamAnon,

It's not possible, this dialog isn't just modal, it's not an app dialog.. i.e. you can't alt-tab away from it or bring it back.

Can you describe the use case in details? i.e. what are you trying to do while, instead of, entering the password?

**Comment by ghost** [comment]
Hi, It just bothers me, it's a QoL/accessibility issue, It's not the fact that it asks me for password but I dislike any sort of blur, DoF, animation, effects, etc in the GUI. I can disable animations easily but not this. If the password window simply opened up without blurring the desktop and without the related movement it would not be a problem.

Sorry, I don't have a machine running Mint at the moment. I'll create a VM later and maybe will provide some screenshots.

Thanks!

**Comment by ghost** [comment]
Here is what I mean. When these dialogs pop up the entire desktop background is blurred and I find it unpleasant. There should be an option to disable this just like there is an option to disable UI animations. It doesn't serve any purpose, it's pointless UI fluff. Thank you.

![mint-secure-desktop-01](https://github.com/user-attachments/assets/fc30bf81-dc89-4687-a1e7-fe4ffe1ccba0)
![mint-secure-desktop-02](https://github.com/user-attachments/assets/60375f54-89a8-40ba-80f9-b63f2d8b99b7)
![mint-secure-desktop-03](https://github.com/user-attachments/assets/8de5b282-0759-4221-b007-860d2cb682ef)

**Comment by clefebvre** [comment]
It's not pointless. It focuses the attention on the action to be performed. These dialogs aren't app dialogs, they're global DE dialogs, which can't be alt-tabbed, or moved, they need to be attended to.

Now that being said, this is done with the shade, but if you disable animations the shade shouldn't be animated. That's a bug right there.

**Comment by ghost** [comment]
So the blurred background is here to stay? I don't need that level of hand holding to focus my attention on an obvious box that pops up in the center of the screen. Was this such a huge problem in the previous versions? This should be an opt-out option. Sad. I can disable this even in Windows. There goes my fav Linux distro.

**Comment by clefebvre** [comment]
It wasn't a thing in the previous version. This used to be done by gnome-polkit which had its own issues.

**Comment by clefebvre** [comment]
Can you show me the setting where this is done in Windows?

**Comment by ghost** [comment]
There are at least two ways of doing this. 

One is in the User Account Control Settings where you can set different levels of notification, one of them is to disable Secure Desktop completely.  

The other one is either in Registry or Group Policy where you can set to elevate admins without secure desktop. I don’t remember this one exactly as I do this while building a custom ISO. Both achieve the same if you are an admin: no blurred background. Though Windows doesn’t have password pop up’s like Linux.  

The point is that this is a major UI annoyance and visually disturbing for some people.
