### ISSUE TITLE
virtual keyboard: when selecting the new cinnamon theme, no letters, symbols or characters are displayed

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint22.1-beta#25]
![v1](https://github.com/user-attachments/assets/2489f769-a81a-4b9d-8ca9-b946f4511da0)

PS.  Maybe it is similar to this [bug](https://github.com/B00merang-Project/macOS-Dark/issues/31)

**Comment by JosephMcc** [comment]
Thanks for linking to a lead on the issue. It does look similar. Will try to get a fix together for it.
