### ISSUE TITLE
Not the latest version of Memtest86+ in GRUB

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint22.1-beta#27]
Memtest86+ v7.00 is available in GRUB menu. The latest version of Memtest86+ is 7.20.
https://www.memtest.org

**Comment by clefebvre** [comment]
That's ok I think. Unless there's a critical reason not to use 7.00. We operate on a frozen base, we won't always fetch the very latest memtest for every single ISO.

**Comment by InfoLibre** [comment]
I don't think there's a critical reason, mainly new hardware are recognized.
