### ISSUE TITLE
The grid option does not appear in the cinamenu with the default theme.

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/mint22.1-beta#29]
In the default theme, the grid option does not appear in the cinnamenu as shown in the image below:
![WhatsApp Image 2024-12-13 at 03 51 03](https://github.com/user-attachments/assets/1e9dea32-cadc-46b6-a31f-2a77c40356a5)

In the Mint-Y-Dark-Blue theme it is ok.
![WhatsApp Image 2024-12-13 at 03 51 27](https://github.com/user-attachments/assets/3e3587d5-3594-460d-a28e-86d4c5d617e9)

**Comment by clefebvre** [comment]
@fredcw

**Comment by fredcw** [comment]
Thanks. Fixed in latest version available [here](https://github.com/fredcw/Cinnamenu)
