### ISSUE TITLE
Mint-Y-Dark* themed applets doesn't use the panel color (and vice-versa)

### ISSUE THREAD

**Issue by contrarybaton60** [linuxmint/mint22.1-beta#31]
![image](https://github.com/user-attachments/assets/c4419d35-752b-49b4-af6a-9966484e1e2c)
basically applets (and right click menu) background color still uses the dark grey from the previous versions while the panel is solid black (I think?)

I don't know if it's intentional or not, I think it's best to keep the dark grey look on the panel.

**Comment by clefebvre** [comment]
It's intentional. The applet bg and panel bg colors are different.

I'm happy to reconsider it for 22.2 if we find something better, but it's intentional.
