### ISSUE TITLE
new cinnamon theme: The context menus of some toolbar icons are displayed in a different color and shape.

### ISSUE THREAD

**Issue by haggen88** [linuxmint/mint22.1-beta#32]
When right clicking on bar icons (mintupdate, mintreport, sticky, warpinator, transmission, onboard and bluetooth) they are still shown in another gray and without rounded corners. 

![V1](https://github.com/user-attachments/assets/c205bfcf-61d9-426b-8f2c-703b13361d35)

vs 

![v2](https://github.com/user-attachments/assets/b38692d9-d532-4c8d-af2f-4e1102d401d8)
-
For consistency, perhaps you could also include the right-click menu on the desktop.

![v2](https://github.com/user-attachments/assets/94413ffb-9cb1-44c2-a9d2-6d2f297bf337)

I take this opportunity to ask: Is it normal that the new cinnamon theme is not the default after installation ?

**Comment by anaximeno** [comment]
> I take this opportunity to ask: Is it normal that the new cinnamon theme is not the default after installation ?

Yes, the Mint-Y theme continues to be the default for Mint, at least for now, the Cinnamon theme is built-in into Cinnamon, therefore used by default when another one isn't available, which tends to be the case for some other distros.

**Comment by JosephMcc** [comment]
The cinnamon theme doesn't effect the elements you are showing. Those menus are themed with the gtk theme which has different capabilities and limitations.

**Comment by clefebvre** [comment]
There's an item on the roadmap to review the dark GTK theme and its colors in Mint 22.2.

If you're interested in this topic make sure you're present on Matrix in the Artists channel.

https://matrix.to/#/#linuxmint-artists:matrix.org
