### ISSUE TITLE
mint-y: cinnamon cornerbar styling

### ISSUE THREAD

**Issue by contrarybaton60** [linuxmint/mint22.1-beta#36]
![bhDo7I0 - Imgur](https://github.com/user-attachments/assets/7eee4d23-d04f-47e3-ba8e-e0cef815dc5b)
this is Mint-L
![HDqZQj8 - Imgur](https://github.com/user-attachments/assets/3bcbea4f-17aa-4c20-a5a4-8ab40402cd5b)
this is Mint-Y
![image](https://github.com/user-attachments/assets/923b4597-53cb-4f78-a386-6d720dbae397)
this is Mint-L in current LMDE

This is likely due to the new cinnamon theme, the old one just uses the one in Mint-Y

**Comment by contrarybaton60** [comment]
eh I kinda like how it looks

**Comment by clefebvre** [comment]
It looks fine to me.. what's the issue exactly?

**Comment by clefebvre** [comment]
Maybe we could get rid of the padding in Mint-Y..

**Comment by contrarybaton60** [comment]
> It looks fine to me.. what's the issue exactly?

Mint-L has a different corner-bar styling compared to X and Y, I'm sorry for not being clear.

**Comment by contrarybaton60** [comment]
This is because Mint-L is inheriting the default Cinnamon theme styling for the corner-bar

(.applet-cornerbar stuff isn't in cinnamon.css, basically)
