### ISSUE TITLE
session crash with nautilus/mysql-client

### ISSUE THREAD

**Issue by BobIH331** [linuxmint/mint22.1-beta#38]
I installed a VirtualBox guest of Mint 22.1 yesterday and restarted a number of times.
During installation I selected to sign in without entering my password.
Today the VirtualBox guest goes to my Desktop but then immediately goes to the log on screen without any action from me.
Entering my password just results in the guest opening 3 different sized black screen and the returning to the log on screen.
The password entered is correct as an incorrect password gives a warning message.

**Comment by BobIH331** [comment]
> During installation I selected to sign in without entering my password.

This is a red herring.  
I have created a new guest, requiring a password at login.
The situation is as before i.e. it logs me into my desktop but then (without any user input) reverts back to the login screen and is then in a loop.

I had adjusted both VirtualBox guest by using the Backup Tool to install Software Selection from my daily driver of Mint 21.3 and think that maybe that is somehow causing the issue.
I will create a new Mint 22.1 guest and carry out some cosmetic alterations and Application additions without using the Backup Tool and report back with my findings.

**Comment by BobIH331** [comment]
The issue occurs when I install the following packages via the Backup Tool

Mysql-client-8.0
mysql-client-core-8.0
nautilus

If only either one is installed then no problem occurs.
However, this is NOT a Mint 22.1 Beta issue.
The problem already exists in VirtualBox guest of Mint 22. 
There is no problem installing both on a Mint 21.3 VirtualBox guest though.

**Comment by clefebvre** [comment]
I can't reproduce the issue.

Fresh 22.1 installation. I add the three packages via the repositories, logout, login work.

What you can do is this:

- Reproduce the issue to get thrown back to the login screen
- Ctrl+Alt+F2 to reach text login (console)
- login in console
- look for errors with `less .xsession-errors`
- exit with `q`

**Comment by BobIH331** [comment]
Good morning Clem.

I created a new VirtualBox guest of the 22.1 beta iso.
Updated it, added guest editions (restart) and then added my user to the vboxusers group (log on user again) re-installed only the 3 'offending' packages via the Backup Tool (restart).
After a minute or so the normal desktop flashes and shows the user log in screen.
I then followed your instructions, however I am not sure what I got is what you need as the terminal exits to my host system, rather than remaining in the guest where the issue is.
Attached is a copy of the xsession errors.

If I can do anything else then please just ask.

Regards,
Bob

________________________________

**Comment by clefebvre** [comment]
Hi @BobIH331, your attachment didn't make it to github.. I can't see it anywhere.

**Comment by clefebvre** [comment]
I've a feeling you're getting this problem:

![image](https://github.com/user-attachments/assets/7814d530-06f4-45b1-9434-cc6c7ee64964)

Check if that package is installed and remove it.

**Comment by BobIH331** [comment]
Sorry for the lack of the attachment.  Please find attached. 
[xsession.txt](https://github.com/user-attachments/files/18256480/xsession.txt)

The removal of gstreamer1.0-vaapi appears to have resolved the issue and the VirtualBox guest now works as expected.
