### ISSUE TITLE
cornerbar Theming mod (Possible PR)

### ISSUE THREAD

**Issue by DaveBlack** [linuxmint/mint22.1-beta#39]
Hi, Based on Cinnamon 22.1 improved theming, created some minor cornerbar cinnamon.css modifications.

## Old
|Unselected|Hover|
:-------------------------:|:-------------------------:
![1 cornerbar (old)](https://github.com/user-attachments/assets/a04b39aa-f177-430b-9978-2deba89dd26b)|![2 cornerbar - hover (old)](https://github.com/user-attachments/assets/82b0a0b3-209f-4248-9761-0d4f55497346)

## New
|Unselected|Hover|
:-------------------------:|:-------------------------:
![3 cornerbar (new)](https://github.com/user-attachments/assets/5f058fe6-67e7-4f21-82ab-791f822b9566)|![4 cornerbar - hover (new)](https://github.com/user-attachments/assets/d1ecbb63-82c7-4ab5-a4d1-0f4bba1bc6c6)

## Old
```
.applet-cornerbar {
  width: 8px;
  background-color: #454545;
  border: 1px solid #333333; }
  .applet-cornerbar.vertical {
    height: 8px; }
  .applet-cornerbar-box {
    background: none; }

.applet-cornerbar-box:hover > .applet-cornerbar {
  background-color: #656565; }
```

## New
```
.applet-cornerbar {
  width: 6px;
  background-color: #1a1a1a; }
  .applet-cornerbar.vertical {
    height: 6px; }
  .applet-cornerbar-box {
    background: none; }

.applet-cornerbar-box:hover > .applet-cornerbar {
  background-color: #454545; }
```

--
Is this the correct file (below link) for submitting a PR, ask since formatting is different?
https://github.com/linuxmint/cinnamon/blob/30ec60b0f6a59e128a9e0c6ed02894baf92b2a41/data/theme/cinnamon-sass/widgets/_applets.scss#L41C4-L41C13

Thank you in advance,
Kind regards.

**Comment by JosephMcc** [comment]
Not sure about this. You've pretty much made the cornerbar invisible unless you hover it.

**Comment by DaveBlack** [comment]
Thanks Joseph your feedback and time is appreciated.

While realise we don't need to do the same, this is pretty much how it functions in Windows 11, keeps out of your way until needed, providing a cleaner UI.

**Comment by clefebvre** [comment]
It looks cleaner indeed but then the feature isn't visible at all. If people don't know it's there, they'll never use it..

**Comment by DaveBlack** [comment]
Thanks Clem for your feedback,

An alternative more muted version, which possible also addresses [this](https://github.com/linuxmint/mint22.1-beta/issues/36#issue-2739393801) issue?

## Old
|Unselected|Hover|
:-------------------------:|:-------------------------:
![1 cornerbar (old)](https://github.com/user-attachments/assets/a04b39aa-f177-430b-9978-2deba89dd26b)|![2 cornerbar - hover (old)](https://github.com/user-attachments/assets/82b0a0b3-209f-4248-9761-0d4f55497346)

## New
|Unselected|Hover|
:-------------------------:|:-------------------------:
![5 cornerbar (new)](https://github.com/user-attachments/assets/aff5deaa-cfc4-46a4-967e-181f8dde535d)|![6 cornerbar - hover (new)](https://github.com/user-attachments/assets/42acdd4c-5090-4594-a074-ca939a40370f)


## Old
```
.applet-cornerbar {
  width: 8px;
  background-color: #454545;
  border: 1px solid #333333; }
  .applet-cornerbar.vertical {
    height: 8px; }
  .applet-cornerbar-box {
    background: none; }

.applet-cornerbar-box:hover > .applet-cornerbar {
  background-color: #656565; }
```

## New
```
.applet-cornerbar {
  width: 6px;
  background-color: #323232; }
  .applet-cornerbar.vertical {
    height: 6px; }
  .applet-cornerbar-box {
    background: none; }

.applet-cornerbar-box:hover > .applet-cornerbar {
  background-color: #454545; }
```

Kind regards.

__
Edit (forgot to mention)...

Rationale: New hover colour matches other Applets hover colour, and 6px size change matches the new default GWL spacing for greater consistency.

In closing, Clem, Joseph, and mint team, hope you and families enjoy a relaxing blessed Christmas and new year.

Best wishes,
David
