### ISSUE TITLE
Design decisions need to be explained

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint22.1-beta#4]
The following decisions/changes should be explained:

- [x] Removal of the Linux Mint cinnamon theme
- [x] Switch to mint-backgrounds-wallpapers
- [x] Hidden menubar in gnome-terminal
- [x] Removal of the percentage in the Cinnamon media OSD
- [x] Switch to Clutter dialogs in Cinnamon 6.4
- [x] Reluctance to accept new configuration options

**Comment by clefebvre** [comment]
### Removal of the Linux Mint cinnamon theme

**Main reason:** To reduce maintenance

The new Cinnamon 6.4 introduces new dialogs, OSDs and components which put a heavy burden on theme maintenance. As we speak, only the default Cinnamon theme and Mint-Y actually fully support it.

Mint-X and Mint-L were adapted to be made compatible but there's more work involved if they want to get their own dialog/OSD styles.

Originally, "Linux Mint" was developed as the default theme for Linux Mint. Back then Mint-X/Mint-Y didn't have a Cinnamon theme. When they got one and Mint eventually switched to Mint-Y, there was no real reason to continue with the "Linux Mint" theme. It was kept because it was there and it didn't really require any work. It does now.

The decision was taken to discontinue it. Anyone can copy it for themselves, maintain it, fork it or turn it into a spice, but it's not a theme we'll continue to maintain.

ref: https://github.com/linuxmint/mint-themes/issues/484

### Switch to mint-backgrounds-wallpapers

**Main reasons:** Improve the selection, make it easier to find backgrounds, reduce maintenance.

Until now each release came with its own set of backgrounds. This was great short-term because it made each release more exciting. Long-term though it meant we had an ever-growing collection of background sets, ordered by release. 

![image](https://github.com/user-attachments/assets/aed99e22-ef9b-4279-8a46-d7a7b0a7cf04)

These sets are about 60MB each so we can't ship with too many of them.... and they're all the same. They all contain a mix of different genres.

Instead of doing that we're moving towards themed sets, with one set per genre.

- Wallpapers, introduced in 22.1, only contains colorful backgrounds.
- Nature, Travel, Objects.. can be added later.

Each set can be updated as we go along to always feature the best. 

Pros: A much nicer selection which is easier to browse.
Cons: Less novelty since we no longer get a full new set each release.

### Hidden menubar in gnome-terminal

**Main reason:** Cosmetic.

The menubar was hidden to make the terminal look simpler and more minimalist. The focus is given on its primary function which is to just type commands and read the output.

Although less discoverable that in the menubar, popular functions such as new-tab and copy are immediately accessible via the context menu.

The menubar also is available in the context menu, and so are the preferences, in which the menubar can be made permanently visible.

Considering the audience for the terminal application it was decided it was OK to make these functions slightly less discoverable. This wouldn't have been done if this was a more casual applications, say a text editor or alike.

### Switch to Clutter dialogs in Cinnamon 6.4

**Main reasons:** Cosmetic, Wayland compatibility

Short-term this was done for cosmetic reasons. The Cinnamon DE is a mixed DE in terms of toolkit and that translates into a mixed DE in terms of visuals. At its heart we've got a set of applications written in Gtk. Around them and on top of them we've got set of desktop widgets written in Clutter.

These are the panels, the menus, the applets, the desklets, the notifications, the workspace management etc..

Because the session itself is around all of that and isn't tied to a particular Gtk application it makes sense for it to adopt the same style as the desktop, not the same style as the apps.

When you open the panel, get to the applet and click Quit, you're using a global widget made in Clutter. It makes sense for the resulting dialog to be global as well, to dim your screen and to be in Clutter, with the same style as the panel you triggered it from.

It's the same idea for the network password and anything global really. The apps are GTK, the desktop is clutter. Anything global should look global.

Things get more arguable when it comes to polkit, because it's an app which is launched in that case and the permission isn't global. This can be argued going forward, though in the case of polkit, moving away from policykit-1-gnome is something we had to do:

- It didn't work in Wayland. In Wayland you couldn't run anything with admin priviledges... thanks to this change, you can.
- policykit-1-gnome isn't actively maintained, it's full of paper cuts when it comes to translations and HiDPI support. We had to move away from it also because of that.

**Comment by clefebvre** [comment]
### Removal of the percentage in the Cinnamon media OSD

**Main reasons:** Cosmetic, simplicity, relevance

Cosmetically the volume OSD looks cleaner and simpler without text.

Relevance. Audio gets louder depending on the content. We might watch a video and the sound volume is perfect.. and then the next video plays and it's way too loud. Your sound volume hasn't changed, yet it was fine, and now it's too loud. The number isn't relevant, it doesn't actually mean much.

Avoiding over-precision. This is something many people do with their TVs. They care about the number too much. Something isn't loud because it's loud, it's loud because the number is high. This leads to pointless arguments or setting the volume according to the number itself, not the actual audible output. You watch a movie, you can't hear it, you increase the volume until it's perfect.. and bam, it's perfect. But wait no, it's not. That number is higher than usual... you don't like that, or someone around doesn't like that, and you landed on 69... I mean, are you going to leave it at 69? really? you're not going to round it up to 70? You're basically caring about a number which really doesn't mean much, and certainly should mean less than what you're actually hearing.. and that says 69, not 50 because that's what you usually use, and not 70 because it doesn't need to be rounded.

Consistency: Although the sound output percentage is still present on many TVs, it's gone in most modern UIs.

Precision: One of the arguments made in favor of showing the percentage is that the user needs to quickly set it to a particular number. This isn't a use case which makes sense since any content can be too loud or not loud enough, on any predetermined percentage. That said, there are quicker and more precise ways to satisfy this use case than relying on the OSD and media keys. The user can set keybindings to set his sound volume to arbitrary values.

This can be done in Keyboard -> Shortcuts -> Custom Shortcuts.

![image](https://github.com/user-attachments/assets/157fa3b9-b031-42b5-a6ba-cd82117be954)

Create a custom shortcut which calls `pactl set-sink-volume @DEFAULT_SINK@ 69%`, assign Ctrl+Alt+6 to it, and voila, every time you press that combo the sound volume will be extactly 69%.

How meaningful or meaningless 69% is depends on users. What's for sure is that reaching an arbitrary percentage is much faster and much more precise with such a keybinding than with a volume knob or the media keys.

**Comment by clefebvre** [comment]
### Reluctance to accept new configuration options

This is pretty hard to explain, so I'll cheat here and quote chatGPT :)

> # Why Accepting New Configuration Options Can Be Bad for Software Development
> 
> Accepting new configuration options in software development can have several downsides, particularly when not carefully planned or justified. Here’s why:
> 
> ## 1. Increased Complexity
> - **Codebase**: Each new option adds complexity to the code, requiring additional logic to handle different cases. This makes the software harder to maintain, debug, and extend.
> - **Testing**: More options mean exponentially more combinations to test. Ensuring reliability across all configurations becomes increasingly difficult.
> 
> ## 2. User Overload
> - Too many configuration options can overwhelm users, making the software harder to use and configure correctly.
> - Users may struggle to understand which options are relevant to their needs, leading to suboptimal setups.
> 
> ## 3. Increased Maintenance Costs
> - New options require ongoing maintenance, including updates to documentation, user interfaces, and support systems.
> - If an option becomes outdated or conflicts with future developments, removing or refactoring it can be costly and disruptive.
> 
> ## 4. Inconsistent User Experience
> - Allowing excessive customization can lead to fragmented experiences where users operate the software in vastly different ways. This inconsistency can make troubleshooting and support more challenging.
> 
> ## 5. Technical Debt
> - Options that cater to edge cases or specific scenarios can introduce technical debt. As the software evolves, these options may hinder progress or force developers to make compromises.
> 
> ## 6. Slower Development
> - Time spent implementing and testing new configuration options could be used to improve core features or fix existing issues.
> - Each new option creates additional dependencies and considerations for future development, potentially slowing down innovation.
> 
> ## Balancing Act
> While configuration options provide flexibility and adaptability for users, they should only be added when:
> - There is a clear and significant user demand.
> - The option aligns with the software’s long-term vision.
> - The benefits outweigh the costs in complexity and maintenance.
> 
> By limiting options to those that deliver meaningful value, developers can focus on creating software that is robust, efficient, and user-friendly.

Now to illustrate this, I'll start by stating the obvious: 

- People are nice, they usually ask nicely, and they do want more options.
- It's extremely easy for us to make people happy and just add yet another configuration option. We're usually talking about just one more settings, one more sentence to translate and one if() statement in the code.
- It's hard to say NO.

So what happens often is that we just add options and make people happy, and short-term that works very well.

In the past, especially during the GTK2 era, there was actually a trend to just add options. We're not putting the finger at any project in particular, we did that ourselves as well. You could look at changelogs and see that most of the improvements weren't necessarily improvements, but just accommodating more preferences and supporting additional niche use cases.

The problem we have now is this:

- We can't reproduce bugs easily because the user isn't running the same code as us. Despite having the same version he's using different configuration options. To him it's not obvious these options are relevant, to us it's not either, so it might take a week, a month or more before someone realizes that and until then he sees a bug but doesn't know how to fix it, we would know but we can't reproduce it..

- There are so many options, sometimes we don't even know the software we maintain supports some of them. This might sound crazy. It is true. I don't think people realize the amount of options we support. Sometimes I'm looking at ricing screenshots and I'm not sure whether I'm looking at extensions or just options. For instance wobbly windows are extensions, but coverflow isn't...

- This is the biggest issue. Sometimes we don't improve the software, we leave it the way it is even though we've an idea on how to make it better, but either that wouldn't support some of the options that are already there, or because there are so many options it's just too costly to do. This is really bad because it affects all users and development pace itself.

- Fairness. It's hard to refuse new options when they're less niche and more popular than options which are already there. There are many features and options in our software which we would have never designed or added ourselves, but because they're already there, we continue to maintain. There's an issue of fairness when these are there and options which aren't, yet feel more important, are refused to be added. We're aware of that and that's a real problem as well.

I think we really need to think about this and clearly differentiate between what's just subjective preference, tuning, necessary options to support niche use cases, etc..

With good defaults, software works well without configuration for most people. When it doesn't for some, we need to accommodate. If a subjective preference is so popular that a huge part of the audience wants it, then we need to accommodate as well. We need to keep cost down though and make sure we don't shoot ourselves in the foot.

We're not finished thinking about this, there's a lot of work involved and a lot of reflection to be had, but I thought talking about this a little bit here might help raise awareness around this.

**Comment by LinuxOnTheDesktop** [comment]
If I may, and if I've got this right: you're proposing having a subset of (what many people call) wallpapers that (the subset) is called . . wallpapers. I think that that - using for the subset a name often applied to the whole set - is a bad idea. How about calling the subset 'colourful' instead?

**Comment by clefebvre** [comment]
hmm.. yeah.. but colorful isn't great either. Some of these are black or neutral.

**Comment by axel358** [comment]
If u don't mind could you explain the logic behind copying GNOME's stylesheet instead of making Mint-Y-something the default cinnamon theme? Now we have a very inconsistent UI, first there's a Cinnamon Mint-Y theme which is darker than the GTK equivalent,  then inside that Cinnamon theme itself we have more inconsistencies with dialogs looking quite out of place as explained in #35, with buttons that look like no other button, and a border radius not present on other modals. What is the need for all this I really can't help but wonder

**Comment by anaximeno** [comment]
> If u don't mind could you explain the logic behind copying GNOME's stylesheet instead of making Mint-Y-something the default cinnamon theme?

Cinnamon is often used with some Gnome tools in other distros than Linux Mint, so it seems reasonable to me for the default theme to look that way (not sure if this was their reasoning as well though).

> (...) Cinnamon theme itself we have more inconsistencies with dialogs looking quite out of place as explained in #35, with buttons that look like no other button, and a border radius not present on other modals. What is the need for all this I really can't help but wonder

The explanation for these changes was made on "**Switch to Clutter dialogs in Cinnamon 6.4**" in the comment above https://github.com/linuxmint/mint22.1-beta/issues/4#issuecomment-2535889814, despite that, these new dialogs can be themed to look more cohesive within the current theme (look on how CBlue, a downloadable theme from the theme settings module, has made it), so I think it's not a big issue, just a matter of updating these themes to support better the new dialogs so they look more cohesive, hence why I made the issue https://github.com/linuxmint/mint22.1-beta/issues/35.

**Comment by contrarybaton60** [comment]
> hmm.. yeah.. but colorful isn't great either. Some of these are black or neutral.

most of the backgrounds in "Wallpapers" look to be 3D renders, naming it "Abstract" is better-ish

you can also move some of the wilma backgrounds to something like "Landscape"
