### ISSUE TITLE
captain: sometimes does not recognize that .deb is already installed

### ISSUE THREAD

**Issue by DirkS2009** [linuxmint/mint22.1-beta#41]
If I install a .deb package with simple double click a replacement for former gdebi opens and I can install the package by press the button "install package" and it will be installed. If I do it with the same .deb package again sometimes it does not recognize that the package was already installed before and it shows again the green button "install package"
But for other .deb packages it works and it shows that the package is already installed.
This behaviour does not happens with gdebi in LM22 Cinnamon.
I use the beta 22.1 as a fresh installation with Cinnamon DE

With this packages you can reproduce it:

It works fine with:
"teamviewer_15.60.3_amd64.deb"
means it recognize it if it's already was installed before

It does not work with:
"freetube_0.22.1_amd64.deb"
means it does not recognize it if it's was already installed before

I hope I was clear. I'm beginner in Linux  since two month. If you need more information please let me know.

**Comment by clefebvre** [comment]
Can you show me a screenshot of the two different states?

Testing here, it doesn't seem to care if the pkg is installed already, for either .deb files.

**Comment by DirkS2009** [comment]
of course. Both are already installed
Teamviewer:
![image](https://github.com/user-attachments/assets/879c6570-efe5-4b7d-bd5e-27872a812bba)
![image](https://github.com/user-attachments/assets/422e9fed-1c80-48df-a3fc-8d73446d2c59)

Freetube:
![image](https://github.com/user-attachments/assets/f400862e-5a93-4921-833b-7ce1c939e3da)
![image](https://github.com/user-attachments/assets/8ea0403c-eb2b-4bf0-8598-3c02d7a21a03)
