### ISSUE TITLE
captain: Can't install .deb driver package from Brother

### ISSUE THREAD

**Issue by DirkS2009** [linuxmint/mint22.1-beta#42]
I need to install "brscan5-1.3.5-0.amd64.deb", which is the driver from Brother for my network scanners. In LM 22 Cinnamon I was able to download and after double click gdebi opens and I was able to press the button "install package"
That does not work any longer in LM 22.1 beta. Either after double click nothing happens or the replacement of gdebi opens but the button "install package" is grey and not pressable. The small button left works, but does not display any additional information below. I need to install via command line with "dpkg -i brscan5-1.3.5-0.amd64.deb" that works.
Also the program should show now, that the package is already installed. Please have a look at my former issue #41.
It's a fresh installation of LM 22.1 beta with Cinnamon DE.

![image](https://github.com/user-attachments/assets/a5999f8d-a183-451b-928d-fca72b59900b)

**Comment by clefebvre** [comment]
Thanks, I can reproduce this. Fix on the way.
