### ISSUE TITLE
artwork: Update cs-nightlight in Mint-L/Mint-Y

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/mint22.1-beta#43]
Receive icon updates from Mint-Y at mint-l-icons and add the cs-nightlight icon.

**Comment by haggen88** [comment]
There is already a PR for the cs-nightlight icon.
- #10

**Comment by haggen88** [comment]
cs-nightlight icon for [Mint-L](https://github.com/linuxmint/mint-l-icons/pull/15) and [Mint-Y](https://github.com/linuxmint/mint-y-icons/pull/452)

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mint22.1-beta/issues/10
