### ISSUE TITLE
Scrolling slowly over the menu items causes tearing

### ISSUE THREAD

**Issue by maniadevice** [linuxmint/mint22.1-beta#45]
There seems to be some kind of tearing in the highlighting of the menu item when scrolling slowly (using touchpad in my case, if it makes any difference). Explained better with the video below. I can't remember if I was using Xorg or Wayland, but I can recheck if needed.

Tried on live USB Linux Mint 22.1-beta Cinnamon DE

https://github.com/user-attachments/assets/d2cb2cfe-5f9c-4dd0-9876-784c53640b53

**Comment by fredcw** [comment]
duplicate of https://github.com/linuxmint/cinnamon/issues/11760

**Comment by maniadevice** [comment]
Closing as it's a duplicate
