### ISSUE TITLE
Typing "xed" in the start menu does not find the text editor anymore

### ISSUE THREAD

**Issue by cz-papoo** [linuxmint/mint22.1-beta#46]
Hello everyone,

I booted _linuxmint-22.1-cinnamon-64bit-beta.iso_ and used it over the last weekend. First of, great to see all the advancements that Linux Mint keeps making!

There is a small problem, and I realize that it's a very minor inconvenience, that I encountered in my daily workflow when opening the text editor `xed`:

1. Press the _super key_ (meta/win) to open the start menu
2. Type "xed", or even "xe"
3. Press `Enter` on the numpad

Up until Linux Mint 22 this worked and the text editor would open.

Unfortunately, in the Linux Mint 22.1 BETA release, this does not work and I have to start typing "text editor" instead for the correct item to appear and be focused in the applications panel of the start menu.

Do you consider this a regression that could or should be addressed in this BETA phase for the upcoming stable release?

While testing, I've noticed that the application's desktop filename has changed:

- `/usr/share/applications/xed.desktop` – (Mint 22, Wilma, `xed_3.6.6+wilma_amd64.deb`)
- `/usr/share/applications/org.x.editor.desktop` – (Mint 22.1 BETA, Xia, `xed_3.8.1+xia_amd64.deb`)

Could this be the reason why entering "xed" does not cause the application to appear in the start menu? Is there any way to restore this behavior for the stable release – maybe some sort of alias?

Thank you for your time, effort and consideration! Have great holidays and a good 2025!

All the best,
Christoph

![screenshot](https://github.com/user-attachments/assets/185d5b92-1356-48c1-a1f3-850b2871aa2c "Typing 'xed' in the start menu does not reveal corresponding app")

**Comment by clefebvre** [comment]
This should have fixed it https://github.com/linuxmint/xed/commit/55f4c058e355e2697401507e3412b0bab2adfa1b

**Comment by cz-papoo** [comment]
Indeed, it works! Thank you!

![image](https://github.com/user-attachments/assets/aa47d65c-aec8-4b90-b809-545156c0d15f)
