### ISSUE TITLE
how to handle issues/bugs because of the base Ubuntu 24.04?

### ISSUE THREAD

**Issue by DirkS2009** [linuxmint/mint22.1-beta#47]
I have two features with issues, which doesn't work any longer, but the reason is Ubuntu 24.04. This features doesn't work any longer in LM22 an LM22.1 beta. How to handle them? At least the second I think is already known by you.

1. Onedrive integration in Online accounts works, but no file access any longer (libmsgraph-0-1 0.2.1 must be upgraded to 0.2.3-1)
![Screenshot from 2024-12-16 15-13-32](https://github.com/user-attachments/assets/14269c60-35f8-4d8d-ab20-5ae24c88cb78)

2. iOS 18 pictures are not possible to open, because libheif 1.15 is to old. Issue is fixed with any version of libheif  1.18.0 and newer

I fixed it for myself and updated them and it works also in LM22.1 beta fine. I believe to know, that you will nothing change on the base Ubuntu 24.04.

If this is still true I only wonder, what users are doing or thinking which try to switch from Windows and install the newest version of LM 22.1. and an former announced functions like Onedrive/Microsoft 365 integration doesn't work any longer. They will not know the background and that the reason was at Microsoft or Apple side. It will be not easy for them to find solutions and could be disapointed. As a beginner in Linux also for me it wasn't easy, but I didn't give up.
If the base will not be changed or adjusted the issues will be also in 22.2, 22.3. It's a long time with a bug.
But I also don't know how Ubuntu will handle this kind of bugs in a LTS release

**Comment by Fantu** [comment]
Report the bug in the Ubuntu bugtracker (if not already present)
If important enough is possible will be fixed
From a fast look both packages have 0 bugs open:
https://launchpad.net/ubuntu/+source/msgraph/+bugs
https://launchpad.net/ubuntu/+source/libheif/+bugs

**Comment by DirkS2009** [comment]
@Fantu: Thanks. For Ubuntu 24.10 both are already updated/fixed. Therefore no bugs open in my opinion.
But I see, it's no LTS. Therefore it seems not important enough for 24.04.

**Comment by clefebvre** [comment]
Please report these upstream to Ubuntu 24.04. They also affect their LTS users.

We can look at it again in 6 months for Mint 22.2. If by then the bug reports haven't moved and there's no action upstream, we can decide to fix this ourselves in Mint directly.

**Comment by DirkS2009** [comment]
Opened the bug reports to Ubuntu 24.04.

https://bugs.launchpad.net/ubuntu/+source/msgraph/+bug/2091959
https://bugs.launchpad.net/ubuntu/+source/libheif/+bug/2091957
