### ISSUE TITLE
cinnamon: panels auto-hide despite setting then to "Always Show Panel"

### ISSUE THREAD

**Issue by jeremiah-k** [linuxmint/mint22.1-beta#49]
First thing I noticed after upgrading from 22 to 22.1 is that in my 3 monitor setup, I have a panel for each one and for Panel Visibility -> Auto-hide panel -> I keep it set to "Always Show Panel".

I tried switching to "Auto Hide Panel" and then back to "Always Show Panel" to see if the behavior would change after re-setting it, but it still only auto hides.

**Comment by anaximeno** [comment]
what's the result of:

```bash
gsettings get org.cinnamon panels-autohide
```
?

**Comment by jeremiah-k** [comment]
> what's the result of:
> 
> ```shell
> gsettings get org.cinnamon panels-autohide
> ```
> 
> ?

```
['1:false', '2:false', '3:false']
```

**Comment by mtwebster** [comment]
It's possible the `panels-enabled` setting is corrupt, and may have overlapping definitions.

![image](https://github.com/user-attachments/assets/2a775f06-c7f9-444e-b814-645de450b399)

- There should be only as many entries as you have panels
- The first number in each entry should be unique.
- the second digit (monitor) : positions should also be unique (there can be only one 0:top panel).
