### ISSUE TITLE
mintupdate: Application crashes

### ISSUE THREAD

**Issue by JesseLeePalser** [linuxmint/mint22.1-beta#51]
Clean install, not a Virtual Machine install of Linux Mint 22.1 Cinnamon Beta.
Beelink SER8 super miniPC.

"Update Manager" does not work well.
I am surprised I was able to update OS.
- It crashes.
- It does not see the Internet sometimes.
- It does not tell user to reboot after Linux Kernel updates.

Let me know if you need something from me, I will post it here.

Jesse

**Comment by mtwebster** [comment]
> - It crashes.

Please check for any related crash information:
https://projects.linuxmint.com/reference/git/bugs/mintreport-crash-info.html

As mentioned on the linked page, if mintupdate or its related tools are crashing, they will show up as 'python3' crashes - use the time/date/pid to associate them.

**Comment by JesseLeePalser** [comment]
Nothing in "Crash reports".
The Update Manager window just disappears (happened twice).
The little icon is still in bottom panel on the right side.

The unable to connect to the Internet happened numerous times.

Update Manager must inform user when reboot is necessary.

Computer hardware below:
https://termbin.com/lzxs

**Comment by clefebvre** [comment]
What's your version of mintupdate?

**Comment by clefebvre** [comment]
Can you describe the steps to reproduce the issue? (i.e how to make it crash).

**Comment by Fantu** [comment]
> Nothing in "Crash reports". The Update Manager window just disappears (happened twice). The little icon is still in bottom panel on the right side.

Open the program from a terminal to see errors in the terminal, should print error also in case the software don't start or close but don't generate a crash report

**Comment by clefebvre** [comment]
Closing as observation.
