### ISSUE TITLE
Clean Install/Not VM - After Installation, Bluetooth Should Automatically Be Turned On

### ISSUE THREAD

**Issue by JesseLeePalser** [linuxmint/mint22.1-beta#52]
Clean install, not a Virtual Machine install of Linux Mint 22.1 Cinnamon Beta.
Beelink SER8 super miniPC.

After installation, Bluetooth should automatically be turned on.

This is going to confuse people who use your Operation System.

Jesse

**Comment by Fantu** [comment]
It is little used and also risky in some cases, so if it is disabled by default and enabled only when needed I think it is a good thing

**Comment by clefebvre** [comment]
It kinda is.

The bluetooth functionality is available and visible by default. The applet shows up without having to do anything and it's ready to be paired. This is consistent with how smartphones or other devices work.
