### ISSUE TITLE
Package Installer sometimes recognizes its already installed same version of .deb

### ISSUE THREAD

**Issue by timfeierabend** [linuxmint/mint22.1-beta#54]
Clean Install on QEMU/KVM, Cinnamon build

Package Installer doesn't recognize a deb it previously installed is installed and has the same version until after after mintupdate 'Refresh' runs.

### To Reproduce
1. Download latest version of Google Chrome
2. Open .deb file from Nemo using Package Installer
3. Install package
4. After installation, before mintupdate refreshes its software cache, re-open the .deb file using Package Installer

### Expected Outcome
Package Installer recognizes package is already installed/same version. (Screenshot from LM22 Cinnamon Stable)
![Screenshot_2024-12-17_05-47-42](https://github.com/user-attachments/assets/e93c0f45-b6cd-405a-9cef-08d134b0fb5a)

### Actual Outcome
Package Installer offers to install the package again.
![Screenshot_2024-12-17_05-55-19](https://github.com/user-attachments/assets/87d73e2a-4369-4e8a-8e1a-1858c35f98b1)
After clicking 'Refresh' in mintupdate:
![Screenshot_2024-12-17_05-57-43](https://github.com/user-attachments/assets/c0f6708a-dd8f-4f46-bc5e-a896b6895809)

**Comment by clefebvre** [comment]
Fixed in captain 1.0.3.

https://github.com/linuxmint/mint22.1-beta/issues/41
