### ISSUE TITLE
Mint-Y observation: No color difference between terminal window and terminal background

### ISSUE THREAD

**Issue by timfeierabend** [linuxmint/mint22.1-beta#55]
When using Mint-Y's dark colors for GNOME Terminal, the new darker defaults result in the same color being used between the terminal window and the terminal background. It looks like a monolith. There is no separation between the window title and the window content.

LM22.1:
![Screenshot_2024-12-17_06-16-49](https://github.com/user-attachments/assets/c7c94c17-13d6-4fcd-b0b5-b25e3087eb65)

LM22:
![Screenshot_2024-12-17_06-13-22](https://github.com/user-attachments/assets/b4a8525d-bcfe-40e5-a07e-5c39635fd7cd)

**Comment by clefebvre** [comment]
Hi @timfeierabend, this is on purpose. It's been changed to get that monolithic look.
