### ISSUE TITLE
webapp-manager: address bar not hidden

### ISSUE THREAD

**Issue by TheCoolerMS3** [linuxmint/mint22.1-beta#57]
![image](https://github.com/user-attachments/assets/d5248f9d-f2be-4529-8c81-2e8d32555fe2)
I noticed a bug where web apps do not have the address bar hidden, like they did in previous releases

![image](https://github.com/user-attachments/assets/b1acafa6-b4a7-45ae-b842-119286885536)
This also results in a strange visual bug in the built in webapp-powered Element client

![image](https://github.com/user-attachments/assets/dafede2a-c55d-491c-9089-7a7de8fa77bd)
Using Chromium instead of Firefox can be a workaround, though I doubt this bugs anyone else as much as it does for me lol

**Comment by haggen88** [comment]
I think [This](https://github.com/linuxmint/webapp-manager/pull/325)  should fix it

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/webapp-manager/pull/325
