### ISSUE TITLE
Celluloid crashes when hardware decoding AV1+Opus WebM video files

### ISSUE THREAD

**Issue by austincbrooks** [linuxmint/mint22.1-beta#58]
**Environment:**
Linux Mint 22.1 Xfce Beta running as a LiveUSB session.  The hardware is a laptop with an i5-1235U processor.  Dual channel memory is installed, so the full integrated Iris Xe graphics are enabled.

**Problem:**
The attached WebM file plays fine with AV1 hardware decoding in Firefox.  Playing the same file with Celluloid causes an instant Celluloid crash.  This happens every time for every AV1 file.  If Celluloid cannot use the kernel-native Intel i915 driver and VAAPI for hardware decoding, I would hope Celluloid could gracefully fall back to the dav1d software decoder.  If I force `hwdec=no` in Celluloid preferences, then the crash doesn't happen.  This crash happens with Mint 22.0 as well.  On Mint 21.3, which does not have kernel support for hardware decoding with Intel Iris Xe/Arc/Alchemist, Celluloid simply starts with dav1d decoding and plays AV1 files without issue.  I recall that Celluloid was downgraded in Mint 22.0 for Gnome/GTK(?) reasons, so I'm not sure if that is related?

Edit: I forgot to mention that running Celluloid from the command line says "Cannot load libcuda.so.1" which suggests the probe has detected the wrong hardware.  This laptop does not have any Nvidia or CUDA components.  The probe should find Intel QuickSync instead.  Forcing `hwdec` to `vaapi` or `auto` don't improve things.  I have attached the log file from `--mpv-log-file=mpv-log.txt` and the interesting stuff starts at line 450.

**Sample AV1 file:**
[AV1-Opus-WebM-sample-for-Celluloid.webm](https://github.com/user-attachments/assets/9e0d6667-5b57-4380-b7e9-4e94d8451833)

[mpv-log.txt](https://github.com/user-attachments/files/18192300/mpv-log.txt)

Thanks for checking, I greatly appreciate everything the Mint team does!

**Comment by leigh123linux** [comment]
Does mpv crash with that file?

```
mpv -v 397191778-9e0d6667-5b57-4380-b7e9-4e94d8451833.webm
```

Maybe try

```
hwdec=auto-safe
```

**Comment by austincbrooks** [comment]
Thanks for replying.  I tried `sudo apt-get update && sudo apt-get install mpv` for the stock MPV player.  It crashed as well, and I've attached the log.  `hwdec=auto-safe` crashed as well.

[mpv-log2.txt](https://github.com/user-attachments/files/18235913/mpv-log2.txt)

**Comment by clefebvre** [comment]
You can upgrade celluloid to the Ubuntu version. I don't think it will help though. But here, just in case:

`apt install celluloid=0.26-1build2`

**Comment by austincbrooks** [comment]
Thank you for the suggestion.  I tried it and got the same `libcuda` error.  This is probably an upstream `mpv` issue.
