### ISSUE TITLE
cinnamon: Problem in the GWL corner.

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/mint22.1-beta#61]
There is still a problem with the grouped window list preview on the left side in the default theme.
![WhatsApp Image 2024-12-20 at 13 54 50](https://github.com/user-attachments/assets/5db7d23e-9483-4cb2-9eb8-26a67c7985e8)

**Comment by JosephMcc** [comment]
Ah! I missed that when I fixed the rest. I was using my HiDPI machine where that's really hard to see. I'll get a fix done for it.
