### ISSUE TITLE
mint-meta-cinnamon bug?

### ISSUE THREAD

**Issue by fblais** [linuxmint/mint22.1-beta#62]
I first installed the XFCE beta, then added the Mate DE with the mint-meta-mate package.
If I try to install the mint-meta-cinnamon, I’m told that pipewire will be removed and pulseaudio will be installed.
I didn’t go further.
Is this a bug in xia’s mint-meta-cinnamon, or it was decided to drop the switch to pipewire and stay with pulseaudio?

Thanks.

**Comment by clefebvre** [comment]
Can you show me the message?

**Comment by fblais** [comment]
There's no message per se, it's just the apt output that show that pipewire will be removed, and pulseaudio is shown in the files that will be installed if I continue.
I have since then reinstalled with the Cinnamon beta edition so I can't show nothing more, sorry.
Hope this helps anyway.

**Comment by clefebvre** [comment]
I'd need to see your dpkg -l output and apt output.

Looking at the dependencies and the default selection between the three editions, I can't explain this. They all ship with pipewire, but none with pulseaudio. Cinnamon and mint-meta-cinnamon don't depend on it.

**Comment by fblais** [comment]
Ok.
I’ll reinstall the XFCE edition and try it again today.

**Comment by fblais** [comment]
Ok, so here's apt output:

francois@xxxxxxxxx:~$ sudo apt install mint-meta-cinnamon
[sudo] Mot de passe de francois :
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Les paquets supplémentaires suivants seront installés : 
  bulky catdoc cinnamon cinnamon-common cinnamon-control-center cinnamon-control-center-data
  cinnamon-l10n cinnamon-screensaver cinnamon-session cinnamon-session-common
  cinnamon-settings-daemon cjs exif folder-color-switcher gir1.2-camel-1.2 gir1.2-caribou-1.0
  gir1.2-cinnamondesktop-3.0 gir1.2-clutter-1.0 gir1.2-cmenu-3.0 gir1.2-cogl-1.0
  gir1.2-coglpango-1.0 gir1.2-cvc-1.0 gir1.2-ecal-2.0 gir1.2-edataserver-1.2 gir1.2-gck-1
  gir1.2-gcr-3 gir1.2-gdesktopenums-3.0 gir1.2-gkbd-3.0 gir1.2-gnomedesktop-3.0
  gir1.2-graphene-1.0 gir1.2-gsound-1.0 gir1.2-gtkclutter-1.0 gir1.2-ical-3.0 gir1.2-keybinder-3.0
  gir1.2-matemenu-2.0 gir1.2-meta-muffin-0.0 gir1.2-nemo-3.0 html2text id3 libasound2-plugins
  libcaribou-common libcaribou0 libcinnamon-control-center1 libcinnamon-menu-3-0 libcjs0 libcvc0
  libgnome-desktop-3-20t64 libgsound0t64 libmate-desktop-2-17t64 libmate-menu2
  libmate-panel-applet-4-1 libmateweather-common libmateweather1t64 libmozjs-115-0t64 libmuffin0
  libnemo-extension1 libpugixml1v5 librda-common librda0 libxcb-res0 libxdo3 libxkbregistry0
  mate-desktop mate-desktop-common mate-menus mate-panel mate-panel-common mate-polkit
  mate-polkit-common mate-user-guide muffin-common nemo nemo-data nemo-fileroller pulseaudio
  python-tinycss2-common python3-magic python3-pam python3-pyasyncore python3-pyinotify
  python3-tinycss2 python3-webencodings python3-xlib python3-xlrd streamer touchegg untex
  xawtv-plugins
Paquets suggérés :
  tk | wish cinnamon-doc gnome-power-manager gnome-screenshot mate-desktop-environment eog totem
  | mp3-decoder pavumeter paprefs python3-pam-dbg python-pyinotify-doc python-tinycss2-doc xawtv
Les paquets suivants seront ENLEVÉS :
  pipewire-alsa pipewire-audio
Les NOUVEAUX paquets suivants seront installés :
  bulky catdoc cinnamon cinnamon-common cinnamon-control-center cinnamon-control-center-data
  cinnamon-l10n cinnamon-screensaver cinnamon-session cinnamon-session-common
  cinnamon-settings-daemon cjs exif folder-color-switcher gir1.2-camel-1.2 gir1.2-caribou-1.0
  gir1.2-cinnamondesktop-3.0 gir1.2-clutter-1.0 gir1.2-cmenu-3.0 gir1.2-cogl-1.0
  gir1.2-coglpango-1.0 gir1.2-cvc-1.0 gir1.2-ecal-2.0 gir1.2-edataserver-1.2 gir1.2-gck-1
  gir1.2-gcr-3 gir1.2-gdesktopenums-3.0 gir1.2-gkbd-3.0 gir1.2-gnomedesktop-3.0
  gir1.2-graphene-1.0 gir1.2-gsound-1.0 gir1.2-gtkclutter-1.0 gir1.2-ical-3.0 gir1.2-keybinder-3.0
  gir1.2-matemenu-2.0 gir1.2-meta-muffin-0.0 gir1.2-nemo-3.0 html2text id3 libasound2-plugins
  libcaribou-common libcaribou0 libcinnamon-control-center1 libcinnamon-menu-3-0 libcjs0 libcvc0
  libgnome-desktop-3-20t64 libgsound0t64 libmate-desktop-2-17t64 libmate-menu2
  libmate-panel-applet-4-1 libmateweather-common libmateweather1t64 libmozjs-115-0t64 libmuffin0
  libnemo-extension1 libpugixml1v5 librda-common librda0 libxcb-res0 libxdo3 libxkbregistry0
  mate-desktop mate-desktop-common mate-menus mate-panel mate-panel-common mate-polkit
  mate-polkit-common mate-user-guide mint-meta-cinnamon muffin-common nemo nemo-data
  nemo-fileroller pulseaudio python-tinycss2-common python3-magic python3-pam python3-pyasyncore
  python3-pyinotify python3-tinycss2 python3-webencodings python3-xlib python3-xlrd streamer
  touchegg untex xawtv-plugins
0 mis à jour, 89 nouvellement installés, 2 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 35,8 Mo dans les archives.
Après cette opération, 213 Mo d'espace disque supplémentaires seront utilisés.
Souhaitez-vous continuer ? [O/n] n
Annulation.

I'm attaching the dpkg -l output in a logfile.
[dpkg_log.txt](https://github.com/user-attachments/files/18231860/dpkg_log.txt)

**Comment by clefebvre** [comment]
Ok, I think it's to do with cinnamon-settings-daemon recommending pulseaudio.

**Comment by clefebvre** [comment]
Fixed in csd 6.4.3
