### ISSUE TITLE
Audio stuttering over HDMI

### ISSUE THREAD

**Issue by joshhansen** [linuxmint/mint22.1-beta#63]
My apologies, this is a Linux Mint 22 bug, but it seemed relevant to 22.1 as it's being put together. Upon upgrading from 21.3 to 22, I experienced stuttering or skipping in audio playback coming from multiple applications (Firefox and Strawberry music player). The audio is output by my TV, which the computer connects to over HDMI.

The problem occurred using default configuration (no pipewire config file). I fiddled with a few config parameters to no success.

I was able to work around it by removing the pipewire packages and using pulseaudio as in 21.3, as described in [the release notes for 22](https://www.linuxmint.com/rel_wilma.php) under "Sound Issues".

This seems like a significant regression and obviously related to the switch to Pipewire in Linux Mint 22, so I thought I'd file it. Could relate to this bug report elsewhere:

- https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3110

Thanks.

**Comment by snaff9** [comment]
Can also repro, this is overall bad for the general LM22 experience.  I spent months trying to find a workaround for this.

**Comment by Qronikarz** [comment]
I also have problems with HDMI, but even worse my default DisplayPort also started to behave the same way.

I know for a fact that in Mint 22 the DisplayPort audio worked well. I don't really remember, but I think for few days 22.1 also worked without issue, but after some updates it got broken and it's full of static noise. I may try the live USB version to check, but right now it is broken.

**Comment by clefebvre** [comment]
I'm sorry you're experiencing this. This is upstream from us and there's no solution for it yet unfortunately.

The pipewire team seems to think this is Debian-specific: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1025453.

I added a link on our own rel notes.

**Comment by joshhansen** [comment]
Thanks for your response @clefebvre .  I added a comment to that Debian issue about my experience hoping to motivate some movement on it and offering my services in debugging.
