### ISSUE TITLE
Vulnerability (not in this Beta)

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint22.1-beta#66]
This has nothing to do with this beta, but reporting it here as I didn’t receive an answer via email.
I sent you an email on Saturday, August 31 this year with the subject starting with "Security alert". Could you recheck it?

**Comment by clefebvre** [comment]
Closing since it's not related.

@carlosmintfan I don't see that email. Either it was dismissed/handled or not received. Can you send it again just in case?

**Comment by carlosmintfan** [comment]
@clefebvre I sent it again. Could you also check your spam folder? Thanks! It comes from the address `of*******s@outlook.com`
