### ISSUE TITLE
Custom theme bugs

### ISSUE THREAD

**Issue by SakiiCode** [linuxmint/mint22.1-beta#68]
1. I have a slightly modified Mint-L icon theme in \~/.icons but gives an error for many (unmodified) icons

<details>

<summary>Screenshot</summary>

![missing_icons2](https://github.com/user-attachments/assets/f46899ce-dc77-4972-9831-a0c0ff57b499)

</details>

2. I have a custom desktop theme installed under /usr/share/themes and it does not have a preview. It has a preview when installed to ~/.themes

<details>

<summary>Screenshot</summary>

![missing_preview](https://github.com/user-attachments/assets/b6bc2232-2b12-41ab-b612-5f74e2d98d78)

</details>

None of these happen in 21.3

**Comment by fblais** [comment]
Have you tried gtk-update-icon-cache?

**Comment by SakiiCode** [comment]
Tried this now and did not do anything
```
gtk-update-icon-cache
sudo gtk-update-icon-cache
sudo update-icon-caches /usr/share/icons/*
sudo update-icon-caches ~/.icons/*
```
The problems persist after a reboot so I don't think it's related to caching

Renaming the icon theme also does not help, so not related to collisions i guess

**Comment by SakiiCode** [comment]
Both of these issues were an error on my side as I copied the themes from a mounted network storage instead of cloning them to the local drive. It messed up the symlinks and the permissions  :(
