### ISSUE TITLE
No notification about 21.3 > 22 upgrade (not Beta related)

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint22.1-beta#69]
Again, a Beta spammer, but what else can I do? There is no info about the 21.3 to 22 upgrade in the system reports app on Linux Mint 21.3. Is this intended? Why, if yes? Can you merge https://github.com/linuxmint/mint-upgrade-info/pull/5, if not?

**Comment by rubenpedev** [comment]
Have you tried this? https://linuxmint-user-guide.readthedocs.io/en/latest/upgrade-to-mint-22.html

**Comment by carlosmintfan** [comment]
@benmpl Thanks, but I know that I can upgrade this way. It‘d be nice if users that don’t regularly read the blog were notified about it though.

**Comment by fblais** [comment]
The standard Linuxmint forum could have been a better place to ask.
https://forums.linuxmint.com/
Just a suggestion.

**Comment by carlosmintfan** [comment]
Ask…I want to make the devs attentive. My PR didn’t get merged…I already brought up this topic in the past when I had a different PR and got the answer I had to change something, now this new PR…doesn’t get merged. I want to know the reason for this. Linux Mint is a great distro and it’d even be greater if this would work.
But, thank you for your suggestion.

**Comment by JosephMcc** [comment]
> Again, a Beta spammer, but what else can I do?

You can stop spamming issues for the Mint beta with unrelated things. Easy fix.

**Comment by carlosmintfan** [comment]
> > Again, a Beta spammer, but what else can I do?
> 
> You can stop spamming issues for the Mint beta with unrelated things. Easy fix.

But that doesn’t fix the upgrade notification problem. Couldn‘t you wait until @clefebvre gets this before closing it?
But if you care more about a clean Beta than an easy and quick fix for the problem I mentioned, I won’t harass you any more about that here. If I  could only get answers from Clem…
