### ISSUE TITLE
The new Cinnamon theme is not the default theme fresh post install

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint22.1-beta#71]
Title.

I was a bit confused, of why I'm not having that cool new design right out of the box, until I realized that I had to go into themes and change the Mint-Y to Cinnamon manually.

1. Notice the calendar's style, still at Mint-Y
![image](https://github.com/user-attachments/assets/521f7f17-0691-46fe-9961-2297364e3c04)

2. Going under Advanced settings:
![image](https://github.com/user-attachments/assets/3e0011fe-28ab-4970-af1d-d5fa1a32f612)

3. Change manually the **Desktop** entry to **cinnamon** ..profit:
![image](https://github.com/user-attachments/assets/113b0581-b17f-4dd7-ba5b-b406e47326f0)

**Comment by contrarybaton60** [comment]
the new cinnamon theme is for distros other than mint that don't have themes set up (Debian, Arch etc)

**Comment by DirkS2009** [comment]
> the new cinnamon theme is for distros other than mint that don't have themes set up (Debian, Arch etc)

If Mint make advertisement with the new look, it should also be included in the default theme. Therefore I understand this "bug" from vajdao very well. I was the same irritated like him. At least there should be a kind of communication/hint to the users about it.
If I look at the reviews about the beta on Youtube, I can see that nobody changed the theme to get the new optic totally.

**Comment by JosephMcc** [comment]
> If Mint make advertisement with the new look, it should also be included in the default theme

I'm pretty sure this was never advertised as a new look for Mint. Mint has a default theme and Cinnamon has always had one of it's own. If that's being advertised as the new default for Mint somewhere, we can't control that.

**Comment by ghost** [comment]
> > If Mint make advertisement with the new look, it should also be included in the default theme
> 
> I'm pretty sure this was never advertised as a new look for Mint. Mint has a default theme and Cinnamon has always had one of it's own. If that's being advertised as the new default for Mint somewhere, we can't control that.

One thing that I'm most known of, is that I always do my survey before posting. Before you close down tickets with such haste, maybe educate yourself

Official website:
https://www.linuxmint.com/rel_xia_whatsnew.php

Made it easier for you @JosephMcc : 
![image](https://github.com/user-attachments/assets/1d072421-7bc0-46d6-9827-e55026a81ede)


Also, this was the last time I ever contributed by any means towards this project, I'm out. Good luck with linux mint.




> > the new cinnamon theme is for distros other than mint that don't have themes set up (Debian, Arch etc)
> 
> If Mint make advertisement with the new look, it should also be included in the default theme. Therefore I understand this "bug" from vajdao very well. I was the same irritated like him. At least there should be a kind of communication/hint to the users about it. If I look at the reviews about the beta on Youtube, I can see that nobody changed the theme to get the new optic totally.

Thank you for standing by me @DirkS2009 - at least, you know what's shakin' :)

**Comment by DirkS2009** [comment]
I also don't understand. See below link:
[https://blog.linuxmint.com/?p=4749](url)

**Comment by ghost** [comment]
@clefebvre can you look into this? @JosephMcc closed it down without actually investigating.. 




> I also don't understand. See below link: [https://blog.linuxmint.com/?p=4749](https://blog.linuxmint.com/?p=4749)

Thanks for clarifying this @DirkS2009 . Basically this blog post + the release [news](https://www.linuxmint.com/rel_xia_whatsnew.php) on the official website supports my claim. I’m not sure how people didn’t spot this already. As I mentioned earlier, in addition to thoroughly investigating and digging into everything, I’m also best known for discovering every single particle of errors (it’s a gift and a curse...), so I'm not opening up tickets by sports or because I have nothing better to do... Thanks for looking into this.

Peace.

**Comment by JosephMcc** [comment]
Not sure what you want anyone to look into. Maybe things could be presented/worded different? The screenshot you showed is for what's new in Cinnamon 6.4 and everything said there is true. The new Cinnamon theme is not the default on Mint. It was never meant to be. This issue isn't going to change it. That's why it's closed. 

> As I mentioned earlier, in addition to thoroughly investigating and digging into everything, I’m also best known for discovering every single particle of errors (it’s a gift and a curse...), so I'm not opening up tickets by sports or because I have nothing better to do...

Well if that's the case you would know there is a difference between Cinnamon and Mint. Even though one does develop the other. Mint-Y is the default theme on Mint. It has been for quite a long time.

**Comment by ghost** [comment]
> Not sure what you want anyone to look into. Maybe things could be presented/worded different? The screenshot you showed is for what's new in Cinnamon 6.4 and everything said there is true. The new Cinnamon theme is not the default on Mint. It was never meant to be. This issue isn't going to change it. That's why it's closed.
> 
> > As I mentioned earlier, in addition to thoroughly investigating and digging into everything, I’m also best known for discovering every single particle of errors (it’s a gift and a curse...), so I'm not opening up tickets by sports or because I have nothing better to do...
> 
> Well if that's the case you would know there is a difference between Cinnamon and Mint. Even though one does develop the other. Mint-Y is the default theme on Mint. It has been for quite a long time.

Uhm.. I know? Are you trolling on purpose? Why are you thinking that I'm mixing up Mint with Cinnamon? Cinnamon is the flagship DE for Mint. Do you know what DE or flagship means at all?

> The new Cinnamon theme is not the default on Mint

You're wrong again, ok it WAS Mint-Y back then, but yes it is the default NOW with 22.1 .. Look, I didn't came up with hallucinating that it's the default, it is the release page and the blog post supporting my claim, aswell as Dirks who also pointed this out!

I see that you're not into reading. Which part of this don't you understand?
![image](https://github.com/user-attachments/assets/616185cf-b36f-404b-ad0b-b385c55a7af7)

Why is it advertised like that? It's very misleading, and make the user think that this is what the new Mint ships right out of the box because heck, "**new default theme**" wording is used everywhere.. **Default**, means **default**, that you don't need to change - hence why it's called **default**... As you can see, its not only me alone, who thought this way.

Why volunteering to a project, if you can't do things because you lack the skill? Why closing down tickets instantly, that YOU don't understand and perhaps there would be another skilled dev who might actually do it? Just because you don't get it, others actually might know how to resolve the issue, and you're definitely not having the rights of closing it down as "completed" by actually not completing it or letting few other knowledgeable people (you know, those who actually do know programming) have a review on this....

Anyways, you seem very ignorant about this, and for real, this is truly my last input from now on. I hope that @clefebvre will look into this, and realize of actually how shady and unaccountable you are and block you out of this project. I was trying to help here by improving the user experience, and point out actual errors, but you guys seem very resistant to any kind of feedback. Then why even have a BETA test if you don’t bother listening? I’m here, wasting my free time helping you build something great, and this is how you react? Instant denial? Okay.. I'm exhausted, tired, and don't have the energy to speak with a potato. Well, good luck with this kind of approach.

**Comment by JosephMcc** [comment]
It's understandable why it's confusing. That is relying on the fact that the reader understands the difference between default for Cinnamon and default for Mint. Those aren't the same but it really isn't written very clearly there if someone is new to Mint.
