### ISSUE TITLE
cinnamon: Darkened background doesn't show in authenication dialogs if effects are disabled

### ISSUE THREAD

**Issue by contrarybaton60** [linuxmint/mint22.1-beta#73]
![Screenshot_mint22 1_2024-12-23_14:56:36](https://github.com/user-attachments/assets/260a0233-f22f-41c9-a2f3-a1ce22880959)
![Screenshot_mint22 1_2024-12-23_14:57:16](https://github.com/user-attachments/assets/cc29a6b1-4a78-4f96-8e64-db286226bb0f)

**Comment by fredcw** [comment]
This is deliberate. https://github.com/linuxmint/mint22.1-beta/issues/24

**Comment by clefebvre** [comment]
is this with Mint-Y?
