### ISSUE TITLE
cinnamon: unable to unhide panel when "Auto hide panel" is set

### ISSUE THREAD

**Issue by contrarybaton60** [linuxmint/mint22.1-beta#74]
https://github.com/user-attachments/assets/8b06ac31-d152-4c66-85de-408938e8688e

This also affects "Intelligently hide panel" when a window is maximized or takes up vertical space.

**Comment by haggen88** [comment]
#28 related

**Comment by mtwebster** [comment]
Do you have just a single monitor or multiple, and how are they aligned? Are you using any display fractional scaling?

**Comment by contrarybaton60** [comment]
> Do you have just a single monitor or multiple, and how are they aligned? Are you using any display fractional scaling?

Single monitor, no fractional scaling (I was using 720p for the vm I think)

**Comment by contrarybaton60** [comment]
https://github.com/user-attachments/assets/aa236382-781c-4a86-9737-97faeb3eb20c

here's another vid with 1080p

**Comment by clefebvre** [comment]
Can you reproduce this on real hardware?

**Comment by contrarybaton60** [comment]
no, I cannot reproduce it from the live environment at least
