### ISSUE TITLE
Long time starting computer...

### ISSUE THREAD

**Issue by ruldc** [linuxmint/mint22.1-beta#75]
Hello! Each new version of linux mint becomes better and more interesting, congratulations to the team for the effort put into this beautiful project, but there are still some problems, they haven't had a solution so far, more precisely, I tested this beta version on two different computers and all this that is, it happens if I start linux after a usb drive or even if it is installed on the computer from the moment I press the start button and until the linux mint logo appears it takes a long time about 15 seconds after that everything goes normally, in the old versions everything started very quickly approx. 2-3 seconds the logo appeared after pressing the power button, please if this problem can be solved, thank you...

**Comment by fblais** [comment]
Did you restart the computer a few times?
Maybe it only happens on the first start.

**Comment by ruldc** [comment]
Welcome I'm still testing linux mint 22.1 beta I installed it on my PC what I noticed is that I installed the updates from the update manager and indeed the logo at startup I noticed that it appears immediately after pressing the start button so the final iso image will also contain these updates when you will release it officially? The boot time is about 46 seconds until everything is complete compared to version 18.3 which started in about 25 seconds it's a difference but this version really contains a lot more things than that old version, please the team if it can include the player in the currency media Xplayer I can't find it in the software manager, thank you, I appreciate your effort in this project and to make this distribution that is really one of the future more efficient...

**Comment by clefebvre** [comment]
`systemd-analyze critical-chain `

**Comment by ruldc** [comment]
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ruldc@ruldc-ThinkCentre-M83:~$ systemd-analyze critical-chain
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

graphical.target @30.866s
└─multi-user.target @30.866s
  └─kerneloops.service @30.820s +45ms
    └─network-online.target @30.803s
      └─NetworkManager-wait-online.service @24.828s +5.974s
        └─NetworkManager.service @18.720s +6.096s
          └─dbus.service @17.292s +1.416s
            └─basic.target @17.253s
              └─sockets.target @17.252s
                └─uuidd.socket @17.252s
                  └─sysinit.target @17.234s
                    └─apparmor.service @8.620s +8.614s
                      └─local-fs.target @8.575s
                        └─run-user-1000.mount @28.159s
                          └─local-fs-pre.target @4.243s
                            └─lvm2-monitor.service @2.737s +1.505s
                              └─systemd-journald.socket @2.693s
                                └─-.mount @2.641s
                                  └─-.slice @2.641s
ruldc@ruldc-ThinkCentre-M83:~$

**Comment by clefebvre** [comment]
This needs more troubleshooting. It's not a bug we can work on, just an observation at this stage.
