### ISSUE TITLE
Wine does not open these Windows programs

### ISSUE THREAD

**Issue by ruldc** [linuxmint/mint22.1-beta#77]
I installed the wine emulator package but it doesn't have all the packages to run these two free programs that I use on Windows, namely Ncorrector and Myplasmcnc, I can't get them to run in linux mint, please test if possible to find a solution in the old versions it worked but now it doesn't want to work at all....

**Comment by fblais** [comment]
Did you install following:
(from https://www.linuxmint.com/rel_xia.php)

**Wine**
To install the complete version of WINE, open a terminal and type:

apt install wine-installer

Among other things, this will install wine-desktop-files, which adds menu entries for regedit, your C:\ drive and other items which are missing from upstream WINE.
