### ISSUE TITLE
xfce: XAppStatusPlugin icons are too small/squashed

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint22.1-beta#8]
OOTB, this should match the size and spacing of the other plugins:

![image](https://github.com/user-attachments/assets/724b6919-e6e8-4a8d-912b-7c27071c52e1)

**Comment by mtwebster** [comment]
fix for preferences: https://github.com/linuxmint/xfce4-xapp-status-plugin/commit/2fa34773b84ae47643013637eb6d8c72fd0eb267
