### ISSUE TITLE
XFCE: login twice

### ISSUE THREAD

**Issue by bittin** [linuxmint/mint22.1-beta#80]
Hey!

With the 22.1 Beta installed in gnome-boxes with the XFCE version i have to login twice to get logged in

**Comment by clefebvre** [comment]
From console, check your ~/.xsession-errors for clues after the failed login.

**Comment by Grauestone** [comment]
I have that very same problem in Linux Mint 20.3 xfce, I was considering installing this 22.1 xfce version to try if it would fix. I wanted to make a detailed testing pf the issue as per instructions before posting on the relevant forum, but I mention it here in case it helps.
System:    Kernel: 5.4.0-200-generic x86_64 bits: 64 compiler: gcc v: 9.4.0 Desktop: Xfce 4.16.0 
           tk: Gtk 3.24.20 wm: xfwm4 dm: LightDM Distro: Linux Mint 20.3 Una 
           base: Ubuntu 20.04 focal
It seems almost always happening when coming back from suspend mode. I wonder if it has anything to do with amd drivers and dual monitor support which i frequently have in my setup...
Any instruction (rookie-compatible ) you might need from me to help troubleshooting, let me know.

**Comment by clefebvre** [comment]
Is gstreamer1.0-vaapi installed?

**Comment by Grauestone** [comment]
> Is gstreamer1.0-vaapi installed?

Yes, I looked it up in the synaptics pckage manager.  In my case, version 1.16.2-2

**Comment by bittin** [comment]
> From console, check your ~/.xsession-errors for clues after the failed login.

Here is that file: https://pastebin.com/0M7xMZ51 

and yeah that package is installed as version 1.24.2

**Comment by clefebvre** [comment]
Ok, that's an issue between Xorg and virtualization then.

You're basically asking Xorg for HW acceleration which your virtual machine doesn't have.

![image](https://github.com/user-attachments/assets/39a5002c-aa33-4b57-9a0e-b5eaca32be0f)


https://linuxmint.com/rel_xia.php

**Comment by bittin** [comment]
> Ok, that's an issue between Xorg and virtualization then.
> 
> You're basically asking Xorg for HW acceleration which your virtual machine doesn't have.
> 
> ![image](https://private-user-images.githubusercontent.com/1138515/398723123-39a5002c-aa33-4b57-9a0e-b5eaca32be0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMTUwMDEsIm5iZiI6MTczNTIxNDcwMSwicGF0aCI6Ii8xMTM4NTE1LzM5ODcyMzEyMy0zOWE1MDAyYy1hYTMzLTRiNTctOWEwZS1iNWVhY2EzMmJlMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjZUMTIwNTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWIxOTM2N2QxZTU0MTgyM2VlZmM5YWNlM2VkZWYzMzE2OGIxNzM3YWMwNTU4OTI3YTE3ODE1MmYyOGMyNjJkMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.itSx3cZGiEW95kZDgS2dzjbb-1pM2bbNxkloFVr4wP0)
> 
> https://linuxmint.com/rel_xia.php

That solved it, thank you :)
