### ISSUE TITLE
Celluloid resizing problem...

### ISSUE THREAD

**Issue by ruldc** [linuxmint/mint22.1-beta#82]
Celluloid is resized regardless of the setting, even if I set it not to resize automatically, the same thing happens, that is, I make it smaller with the mouse and after closing the program and restarting, celluloid returns to its large form by itself....

**Comment by ruldc** [comment]
Ce program as putea instala pentru captură ecran sa va arat mai exact detalii...?

**Comment by ruldc** [comment]
What program can I install to record the screen so I can provide more details?

**Comment by clefebvre** [comment]
Celluloid isn't something we maintain. This could change in the future though since it moved to libAdwaita.

As it is right now, this won't be worked on.
