### ISSUE TITLE
mintinstall & cinnamon: with effects disabled, cancelling the installation of a program would bug out

### ISSUE THREAD

**Issue by contrarybaton60** [linuxmint/mint22.1-beta#89]
https://github.com/user-attachments/assets/66f00c8a-f8d6-40a8-ad72-c3637a39da07

**Comment by clefebvre** [comment]
What's your exact Cinnamon version?

**Comment by mtwebster** [comment]
I can't reproduce this - can you provide system info

**Comment by contrarybaton60** [comment]
https://termbin.com/74tp

**Comment by contrarybaton60** [comment]
I think this due to virtual machine rendering, I don't think it should happen on real hardware (unless if it's like a decade old)

**Comment by clefebvre** [comment]
I can't see how the effects, or lack of effects, would impact the result of pkexec's agent..

**Comment by contrarybaton60** [comment]
I don't know either if I'm being honest, I feel like it's one of those bugs where the problem seems so out of place there doesn't seem to be reason why

**Comment by contrarybaton60** [comment]
also none of the individual options seem to be the problem, only disabling all the effects as a whole

**Comment by mtwebster** [comment]
This may not have anything to do with the pkit agent, but with mintinstall not responding to the operation being cancelled.

Can you run this from a terminal and report the output while reproducing this:
```
DEBUG=1 mintinstall
```

**Comment by contrarybaton60** [comment]
https://github.com/user-attachments/assets/3fad1baf-01e5-4329-9e09-aee0ec85abe0

**Comment by contrarybaton60** [comment]
https://www.youtube.com/watch?v=zooP4uApAfw
another part to this, file too big for github

**Comment by contrarybaton60** [comment]
https://pastebin.com/xVsD1QVB
full log

**Comment by contrarybaton60** [comment]
![image](https://github.com/user-attachments/assets/166b84eb-8faa-45d2-beec-6e2ff723102e)

**Comment by mtwebster** [comment]
I can reproduce with llvmpipe (software rendering) graphics
