### ISSUE TITLE
Artwork improvements missing 

### ISSUE THREAD

**Issue by viveksreedharan88** [linuxmint/mint22.1-beta#91]
I upgraded to 22.1 beta. I see new artworks missing under backgrounds. Wallpapers folder is missing

**Comment by clefebvre** [comment]
The upgrade isn't opened yet.

You can install mint-backgrounds-wallpapers.

**Comment by viveksreedharan88** [comment]
No worries Clem! This ain't a big issue though! Just thought of letting u
guys know!
