### ISSUE TITLE
Power modes are not enabled by default

### ISSUE THREAD

**Issue by viveksreedharan88** [linuxmint/mint22.1-beta#92]
The power modes are neither showing up in battery icon of panel nor getting enabled in power settings.

**Comment by clefebvre** [comment]
Is `power-profiles-daemon` installed?

Can you show a screenshot of the power settings?

**Comment by viveksreedharan88** [comment]
Hi Clem,

I installed it and then it got enabled. But shouldn't this be installed and
enabled automatically?

**Comment by contrarybaton60** [comment]
> Is `power-profiles-daemon` installed?
> 
> Can you show a screenshot of the power settings?

It doesn't seem to be in the live environment
https://imgur.com/0InWrwX

**Comment by viveksreedharan88** [comment]
Well! If it'll be available in stable version, then it's ok. Sounds good to me! You may close this issue.
